apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: DevWorkspaceTemplate
objects: 
  - apiVersion: workspace.devfile.io/v1alpha2
    kind: DevWorkspaceTemplate
    metadata:
      name: che-code-web-frontend
      namespace:  ${USERNAME}-devspaces
    labels:
      demo: scaling
    spec:
      commands:
        - apply:
            component: che-code-injector
          id: init-container-command
        - exec:
            commandLine: >-
              nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
              2>&1 &
            component: che-code-runtime-description
          id: init-che-code-command
      components:
        - attributes:
            app.kubernetes.io/component: che-code-runtime
            app.kubernetes.io/part-of: che-code.eclipse.org
            controller.devfile.io/container-contribution: true
          container:
            cpuRequest: 30m
            env:
              - name: CHE_DASHBOARD_URL
                value: https://devspaces.apps.cluster-7c4sw.7c4sw.sandbox1601.opentlc.com
              - name: CHE_PLUGIN_REGISTRY_URL
                value: >-
                  https://devspaces.apps.cluster-7c4sw.7c4sw.sandbox1601.opentlc.com/plugin-registry/v3
              - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
                value: http://plugin-registry.openshift-operators.svc:8080/v3
              - name: CLUSTER_CONSOLE_URL
                value: >-
                  https://console-openshift-console.apps.cluster-7c4sw.7c4sw.sandbox1601.opentlc.com
              - name: CLUSTER_CONSOLE_TITLE
                value: OpenShift console
              - name: OPENVSX_REGISTRY_URL
                value: ''
            memoryRequest: 256Mi
            sourceMapping: /projects
            cpuLimit: 500m
            volumeMounts:
              - name: checode
                path: /checode
            memoryLimit: 1024Mi
            image: >-
              registry.redhat.io/devspaces/udi-rhel8@sha256:b1f112760b2640b5e8612869536a000612837e8e247c74d3d99e9fcfbc56d2f3
            endpoints:
              - attributes:
                  cookiesAuthEnabled: true
                  discoverable: false
                  type: main
                  urlRewriteSupported: true
                exposure: public
                name: che-code
                protocol: https
                secure: false
                targetPort: 3100
              - attributes:
                  discoverable: false
                  urlRewriteSupported: false
                exposure: public
                name: code-redirect-1
                protocol: http
                targetPort: 13131
              - attributes:
                  discoverable: false
                  urlRewriteSupported: false
                exposure: public
                name: code-redirect-2
                protocol: http
                targetPort: 13132
              - attributes:
                  discoverable: false
                  urlRewriteSupported: false
                exposure: public
                name: code-redirect-3
                protocol: http
                targetPort: 13133
          name: che-code-runtime-description
        - name: checode
          volume: {}
        - container:
            cpuRequest: 30m
            command:
              - /entrypoint-init-container.sh
            env:
              - name: CHE_DASHBOARD_URL
                value: https://devspaces.apps.cluster-7c4sw.7c4sw.sandbox1601.opentlc.com
              - name: CHE_PLUGIN_REGISTRY_URL
                value: >-
                  https://devspaces.apps.cluster-7c4sw.7c4sw.sandbox1601.opentlc.com/plugin-registry/v3
              - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
                value: http://plugin-registry.openshift-operators.svc:8080/v3
              - name: CLUSTER_CONSOLE_URL
                value: >-
                  https://console-openshift-console.apps.cluster-7c4sw.7c4sw.sandbox1601.opentlc.com
              - name: CLUSTER_CONSOLE_TITLE
                value: OpenShift console
              - name: OPENVSX_REGISTRY_URL
                value: ''
            memoryRequest: 32Mi
            sourceMapping: /projects
            cpuLimit: 500m
            volumeMounts:
              - name: checode
                path: /checode
            memoryLimit: 256Mi
            image: >-
              registry.redhat.io/devspaces/code-rhel8@sha256:acceb48348adf47600c23d3f0ae9a9371d512645b1c277250ff182cf712141fe
          name: che-code-injector
      events:
        postStart:
          - init-che-code-command
        preStart:
          - init-container-command
parameters:
- description: Username
  name: USERNAME              