apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: DevWorkspaceTemplate
objects: 
  - apiVersion: workspace.devfile.io/v1alpha2
    kind: DevWorkspaceTemplate
    metadata:
      annotations:
        che.eclipse.org/components-update-policy: managed
        che.eclipse.org/plugin-registry-url: >-
          https://devspaces.apps.cluster-wgtwf.wgtwf.sandbox1935.opentlc.com/plugin-registry/v3/plugins/eclipse/che-theia/latest/devfile.yaml
      name: theia-workspace
      namespace: ${USERNAME}-devspaces
    spec:
      commands:
        - apply:
            component: remote-runtime-injector
          id: init-container-command
      components:
        - attributes: {}
          container:
            cpuRequest: 100m
            env:
              - name: THEIA_PLUGINS
                value: local-dir:///plugins
              - name: HOSTED_PLUGIN_HOSTNAME
                value: 0.0.0.0
              - name: HOSTED_PLUGIN_PORT
                value: '3130'
              - name: THEIA_HOST
                value: 127.0.0.1
              - name: CHE_DASHBOARD_URL
                value: https://devspaces.apps.cluster-wgtwf.wgtwf.sandbox1935.opentlc.com
              - name: CHE_PLUGIN_REGISTRY_URL
                value: >-
                  https://devspaces.apps.cluster-wgtwf.wgtwf.sandbox1935.opentlc.com/plugin-registry/v3
              - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
                value: http://plugin-registry.openshift-operators.svc:8080/v3
            sourceMapping: /projects
            cpuLimit: 1500m
            volumeMounts:
              - name: plugins
                path: /plugins
              - name: theia-local
                path: /home/theia/.theia
            memoryLimit: 512M
            image: >-
              registry.redhat.io/devspaces/theia-rhel8@sha256:0f550ba6a88ca8e29bbba1c41829013f88208f47c169f9d1db911866285c684d
            endpoints:
              - attributes:
                  cookiesAuthEnabled: true
                  discoverable: false
                  type: main
                  urlRewriteSupported: true
                exposure: public
                name: theia
                protocol: https
                secure: false
                targetPort: 3100
              - attributes:
                  cookiesAuthEnabled: true
                  discoverable: false
                  type: webview
                  unique: true
                  urlRewriteSupported: true
                exposure: public
                name: webviews
                protocol: https
                secure: false
                targetPort: 3100
              - attributes:
                  cookiesAuthEnabled: true
                  discoverable: false
                  type: mini-browser
                  unique: true
                  urlRewriteSupported: true
                exposure: public
                name: mini-browser
                protocol: https
                secure: false
                targetPort: 3100
              - attributes:
                  discoverable: false
                  type: ide-dev
                  urlRewriteSupported: true
                exposure: public
                name: theia-dev
                protocol: http
                targetPort: 3130
              - attributes:
                  discoverable: false
                  urlRewriteSupported: true
                exposure: public
                name: theia-redirect-1
                protocol: http
                targetPort: 13131
              - attributes:
                  discoverable: false
                  urlRewriteSupported: true
                exposure: public
                name: theia-redirect-2
                protocol: http
                targetPort: 13132
              - attributes:
                  discoverable: false
                  urlRewriteSupported: true
                exposure: public
                name: theia-redirect-3
                protocol: http
                targetPort: 13133
              - attributes:
                  cookiesAuthEnabled: true
                  discoverable: false
                  type: collocated-terminal
                  urlRewriteSupported: true
                exposure: public
                name: terminal
                protocol: wss
                secure: false
                targetPort: 3333
            mountSources: true
          name: theia-ide
        - name: plugins
          volume: {}
        - name: theia-local
          volume: {}
        - attributes: {}
          container:
            command:
              - /go/bin/che-machine-exec
              - '--url'
              - 127.0.0.1:3333
            cpuLimit: 500m
            cpuRequest: 30m
            env:
              - name: CHE_DASHBOARD_URL
                value: https://devspaces.apps.cluster-wgtwf.wgtwf.sandbox1935.opentlc.com
              - name: CHE_PLUGIN_REGISTRY_URL
                value: >-
                  https://devspaces.apps.cluster-wgtwf.wgtwf.sandbox1935.opentlc.com/plugin-registry/v3
              - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
                value: http://plugin-registry.openshift-operators.svc:8080/v3
            image: >-
              registry.redhat.io/devspaces/machineexec-rhel8@sha256:30dff710196f7061066932a69ca4d3f680d88c95e2883dd5809d43d3e4a8e39f
            memoryLimit: 128Mi
            memoryRequest: 32Mi
            sourceMapping: /projects
          name: che-machine-exec
        - container:
            cpuLimit: 500m
            cpuRequest: 30m
            env:
              - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
                value: /remote-endpoint/plugin-remote-endpoint
              - name: REMOTE_ENDPOINT_VOLUME_NAME
                value: remote-endpoint
              - name: CHE_DASHBOARD_URL
                value: https://devspaces.apps.cluster-wgtwf.wgtwf.sandbox1935.opentlc.com
              - name: CHE_PLUGIN_REGISTRY_URL
                value: >-
                  https://devspaces.apps.cluster-wgtwf.wgtwf.sandbox1935.opentlc.com/plugin-registry/v3
              - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
                value: http://plugin-registry.openshift-operators.svc:8080/v3
            image: >-
              registry.redhat.io/devspaces/theia-endpoint-rhel8@sha256:e1b120b445f5ac484ba90c04357a2b218e4c990bbdbedbcdb347565c29cb1ea8
            memoryLimit: 128Mi
            memoryRequest: 32Mi
            sourceMapping: /projects
            volumeMounts:
              - name: plugins
                path: /plugins
              - name: remote-endpoint
                path: /remote-endpoint
          name: remote-runtime-injector
        - name: remote-endpoint
          volume:
            ephemeral: true
      events:
        preStart:
          - init-container-command
parameters:
- description: Username
  name: USERNAME              